AAFC-BICoE/seqdb-api

README.md, pom.xml
=> Fixed h2 version to 1.4.196

.gitignore
https://redmine.biodiversity.agr.gc.ca/issues/12898
-Added the eclipse-generated filenames to .gitignore
=> Feedback Support #12898 Update .gitignore with Eclipse files

src/main/resources/ssl.example.yml
https://redmine.biodiversity.agr.gc.ca/issues/11917
-Added example ssl config file explaining how to configure a self-signed
certificate.
=> Feedback Feature #11917 Support https connections

README.md
https://redmine.biodiversity.agr.gc.ca/issues/14423
Added lombok IDE setup link.
=> Feedback Support #14423 Add instructions for setting up lombok in IDE

docs/liquibase.adoc, pom.xml, src/main/resources/liquibase.example.properties
=> Support 14929 liquibase maven plugin should use the version provided by spring boot

README.md, RELEASE_NOTES.md, docs/running.adoc
Added minimal information to README and prepare for 1.2 release
=> Support #15070 Prepare release note for 1.2 and update README

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrPrimerDto.java
PcrPrimerDto
https://redmine.biodiversity.agr.gc.ca/issues/15352
-Changed java.util.Date to java.sql.Date in PcrPrimerDto.
=> Feedback Bug #15352 Use java.sql.Date instead of java.util.Date in

pom.xml
Update dependencies to include bug fixes
=> Support #15447 Update dependencies

docs/liquibase.adoc
https://redmine.biodiversity.agr.gc.ca/issues/15668
Updated Liquibase documentation to define guidelines
=> Support 15668 Define guidelines liquibase migration script

src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java, src/main/java/ca/gc/aafc/seqdb/api/dto/vocabularies/BaseVocabularyDto.java, src/main/java/ca/gc/aafc/seqdb/api/repository/DtoReadonlyRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/VocabularyReadOnlyRepository.java, src/test/java/ca/gc/aafc/seqdb/api/repository/VocabularyDtoRepositoryIT.java
https://redmine.biodiversity.agr.gc.ca/issues/15093
=> Support #15093 expose vocabularies 

src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java
already have it
https://redmine.biodiversity.agr.gc.ca/issues/15827
-Added rsql filters to remaining repositories.
=> Feedback Feature #15827 Add RSQL filtering to repositories that don't

docs/liquibase.adoc
https://redmine.biodiversity.agr.gc.ca/issues/16217
- Added documentation highlighting how Liquibase contexts work and how
to use and change them.
=> Support #16217 - Add more Liquibase Initial Data

src/main/java/ca/gc/aafc/seqdb/api/security/keycloak/KeycloakAuthConfig.java, src/main/java/ca/gc/aafc/seqdb/api/security/ldap/LdapAndLocalDbAuthConfig.java
authentication
https://redmine.biodiversity.agr.gc.ca/issues/16673
-Added config to disable auth on the json-schema endpoints.
=> Feedback Support #16673 Json schema should be available without

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/repository/jpa/JpaDtoRepository.java
exception
https://redmine.biodiversity.agr.gc.ca/issues/16760
-Replaced ModelMapper instance with ObjectMapper.
-Removed ModelMapper dependency.
=> Feedback Bug #16760 Operations endpoint fails with Model Mapper

src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java, src/main/java/ca/gc/aafc/seqdb/api/dto/StepResourceDto.java
https://redmine.biodiversity.agr.gc.ca/issues/16756
- Uncommented the sample relationship in the Step Resource.
- Added the relationship in the Resource Repository.
=> Feature #16756 - Expose StepResource Sample Link

src/main/resources/application.yml, src/test/java/ca/gc/aafc/seqdb/api/rest/BaseJsonApiIntegrationTest.java, src/test/java/ca/gc/aafc/seqdb/api/rest/IncludeParamLookupBehaviorIT.java
https://redmine.biodiversity.agr.gc.ca/issues/16778
-Changed the default lookup behavior to be the same as Crnk 2.
=> Feedback Bug #16778 404 error response when sorting or filtering

pom.xml
Add scm config and release plugin. distributionManagement will be set on the CI platform.
=> Support #16544 Add maven publish plugin to upload articfacts to archiva

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java
https://redmine.biodiversity.agr.gc.ca/issues/16804
- Added a temporary repository to retrieve the newest crnk version with
the required changes.
- Toggled the new "setIncludeChangedRelationships" property in the
module.
=> Support #16804 - Improve Bulk Add Performance for Step Resource

src/main/resources/application.yml
https://redmine.biodiversity.agr.gc.ca/issues/18133
-Added config to suppress com.github.tennaito.rsql logs, other than
error logs.
=> Feedback Support #18133 Suppress com.github.tennaito.rsql logs

.gitignore, .travis.yml, Dockerfile, pom.xml
=> 19956 bump to java 11

src/main/java/ca/gc/aafc/seqdb/api/entities/PreLibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrepBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/NgsIndex.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pooledlibraries/LibraryPool.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pooledlibraries/LibraryPoolContent.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/Chain.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/ChainStepTemplate.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/StepResource.java
https://redmine.biodiversity.agr.gc.ca/issues/20025
Removed the import serializable, serializable interfaces, and serializable long for each of the classes in the entity directory.
=> Support_20025_non_serializable_fields_in_serializable_classes

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/entities/ContainerType.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrPrimer.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrProfile.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PreLibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Product.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Protocol.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Sample.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/Chain.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/StepTemplate.java
Suppresses "EI_EXPOSE_REP", "EI_EXPOSE_REP2" for entity classes
=> 20019 update spotbug rules

pom.xml, src/main/resources/application.yml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/1-Add_Javers_audit_tables.xml
https://redmine.biodiversity.agr.gc.ca/issues/20094
-Updated dina-base-api version in pom.
-Added javers yml config and liquibase migration.
=> Feedback Support #20094 Update to dina-base-api v0.33

.travis.yml, docs/liquibase.adoc, local/docker-compose.yml.example, src/main/resources/db/changelog/db.changelog-init.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/sample-data/1-Add_Sample_Data.xml, src/test/resources/init-db.sql
-Added sample data migration
-Updated existing tables creations to add a default UUID value.
-Updated docs for sample-data liquibase context.
=> Feedback 20203

README.md
=> 21083 update readme

Dockerfile
Removed multistage part from Dockerfile
=> 21177 Remove multistage build from Dockerfile

pom.xml, src/main/resources/application.yml, src/test/java/ca/gc/aafc/seqdb/api/repository/ProtocolResourceRepositoryIT.java
https://redmine.biodiversity.agr.gc.ca/issues/22642
=> 22642 update to dina base 0.54

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/service/ContainerTypeService.java, src/main/java/ca/gc/aafc/seqdb/api/service/MolecularSampleService.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrPrimerService.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrProfileService.java, src/main/java/ca/gc/aafc/seqdb/api/service/PreLibraryPrepService.java, src/main/java/ca/gc/aafc/seqdb/api/service/ProductService.java, src/main/java/ca/gc/aafc/seqdb/api/service/ProtocolService.java, src/main/java/ca/gc/aafc/seqdb/api/service/RegionService.java, src/main/java/ca/gc/aafc/seqdb/api/service/libraryprep/IndexSetService.java, src/main/java/ca/gc/aafc/seqdb/api/service/libraryprep/LibraryPrepBatchService.java, src/main/java/ca/gc/aafc/seqdb/api/service/libraryprep/LibraryPrepService.java, src/main/java/ca/gc/aafc/seqdb/api/service/libraryprep/NgsIndexService.java, src/main/java/ca/gc/aafc/seqdb/api/service/pooledlibraries/LibraryPoolContentService.java, src/main/java/ca/gc/aafc/seqdb/api/service/pooledlibraries/LibraryPoolService.java, src/main/java/ca/gc/aafc/seqdb/api/service/workflow/ChainService.java, src/main/java/ca/gc/aafc/seqdb/api/service/workflow/ChainStepTemplateService.java, src/main/java/ca/gc/aafc/seqdb/api/service/workflow/ChainTemplateService.java, src/main/java/ca/gc/aafc/seqdb/api/service/workflow/StepResourceService.java, src/main/java/ca/gc/aafc/seqdb/api/service/workflow/StepTemplateService.java
https://redmine.biodiversity.agr.gc.ca/issues/23072
=> 23072 update to dina base 0.57

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularSampleDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularSample.java, src/main/java/ca/gc/aafc/seqdb/api/external/ExternalResourceProviderImplementation.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainStepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ContainerTypeRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/IndexSetRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolContentRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/NgsIndexRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrPrimerRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProductRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProtocolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/RegionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepResourceRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/3-Add_external_relationship_to_MolecularSample.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/rest/MolecularSampleJsonApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23110
=> 23110 add external relationship to molecular sample

src/main/java/ca/gc/aafc/seqdb/api/dto/PreLibraryPrepDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PreLibraryPrep.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/4-Update_column_field_targetDpSize_to_targetBpSize.xml
https://redmine.biodiversity.agr.gc.ca/issues/23166
=> 23166 update column/field target dp size to target bp size

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularSampleDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularSample.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/5-Remove_SampleType.xml
https://redmine.biodiversity.agr.gc.ca/issues/23195
=> 23195 remove sample type

src/main/resources/db/changelog/migrations/1-Add_Javers_audit_tables.xml, src/main/resources/db/changelog/migrations/2-Rename_samples_table.xml, src/main/resources/db/changelog/migrations/3-Add_external_relationship_to_MolecularSample.xml, src/main/resources/db/changelog/migrations/4-Update_column_field_targetDpSize_to_targetBpSize.xml
https://redmine.biodiversity.agr.gc.ca/issues/23196
=> 23196 missing context in migration file changeset

src/main/resources/application.yml, src/main/resources/db/changelog/db.changelog-init.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/initial-data/1-Initial_workflow_data.xml
https://redmine.biodiversity.agr.gc.ca/issues/23199
=> seperateinitial data

src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/6-Create_PcrBatch_entity.xml
https://redmine.biodiversity.agr.gc.ca/issues/23202
=> 23202 create pcr batch entity

src/main/java/ca/gc/aafc/seqdb/api/dto/ThermocyclerProfileDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/ThermocycleProfile.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrepBatch.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/VocabularyReadOnlyRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/ThermocyclerProfileService.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/7-Rename_PcrProfile_to_ThermocyclerProfile.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/ThermocyclerProfileFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/23207
=> 23207 rename pcr profile to thermocycler profile

src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrReaction.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/8-Create_PcrReaction_entity.xml
https://redmine.biodiversity.agr.gc.ca/issues/23211
=> 23211 create pcr reaction entity

src/main/java/ca/gc/aafc/seqdb/api/repository/ChainRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainStepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ContainerTypeRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/IndexSetRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolContentRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/NgsIndexRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrPrimerRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProductRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProtocolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/RegionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepResourceRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java
https://redmine.biodiversity.agr.gc.ca/issues/23203
=> 23203 seqdb api start up issue

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrReaction.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/VocabularyReadOnlyRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrBatchService.java, src/main/resources/db/changelog/migrations/6-Create_PcrBatch_entity.xml, src/test/java/ca/gc/aafc/seqdb/api/BaseIntegrationTest.java, src/test/java/ca/gc/aafc/seqdb/api/repository/ContainerTypeResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/IndexSetRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolContentRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/NgsIndexRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/ProductResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/ProtocolResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/SimpleFilterHandlerIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/VocabularyDtoRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/PcrBatchFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23218
=> 23218 create pcr batch dto repo and service

src/main/resources/db/changelog/initial-data/1-Initial_workflow_data.xml
https://redmine.biodiversity.agr.gc.ca/issues/23237
=> 23237 change initial-data uuids

src/main/resources/db/changelog/db.changelog-init.xml
https://redmine.biodiversity.agr.gc.ca/issues/23238
=> 23238 remove h2 migrations

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/9-Add_2_missing_fields_to_PCRBatch.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/PcrBatchFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23260
=> 23260 add 2 missing fields to pcr batch

src/main/java/ca/gc/aafc/seqdb/api/dto/ChainStepTemplateDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/ChainTemplateDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/ContainerTypeDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/IndexSetDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPoolContentDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPoolDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPrepBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPrepDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularSampleDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/NgsIndexDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/PcrPrimerDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/PreLibraryPrepDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/StepResourceDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/StepTemplateDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/ThermocyclerProfileDto.java, src/test/java/ca/gc/aafc/seqdb/api/rest/IncludeParamLookupBehaviorIT.java, src/test/java/ca/gc/aafc/seqdb/api/rest/MolecularSampleJsonApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/rest/PreLibraryPrepJsonApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23253
=> 23253 follow naming convention of other modules for json resource

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrReactionDto.java, src/main/java/ca/gc/aafc/seqdb/api/external/ExternalResourceProviderImplementation.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrReactionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrReactionService.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrReactionRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/MolecularSampleTestFixture.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrReactionTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23286
=> 23286 create pcr reaction dto repo and service

src/test/java/ca/gc/aafc/seqdb/api/BaseIntegrationTest.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/PcrPrimerOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/RegionOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrPrimerTestFixture.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/RegionTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/19623
=> 19623 create open api3 file for pcr primer and region

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainStepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ContainerTypeRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/IndexSetRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolContentRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/NgsIndexRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrPrimerRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrReactionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProductRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProtocolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/RegionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepResourceRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/PcrPrimerOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/RegionOpenApiIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23312
=>  23312 update to dina-base 0.60

src/main/java/ca/gc/aafc/seqdb/api/entities/SeqBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/11-Add_seqBatch_entity.xml
https://redmine.biodiversity.agr.gc.ca/issues/23352
=> 23352 add seq batch entity

src/main/java/ca/gc/aafc/seqdb/api/dto/SeqBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/repository/SeqBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/SeqBatchService.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/SeqBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/SeqBatchFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/SeqBatchTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23366
=> 23366 add seq batch dto service and repo

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/ThermocyclerProfileDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/SeqBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/ThermocyclerProfile.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrepBatch.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/VocabularyReadOnlyRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/ThermocyclerProfileService.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/ThermocyclerProfileFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/23370
=> 23370 Rename entity ThermocycleProfile to ThermocyclerProfile

src/main/java/ca/gc/aafc/seqdb/api/dto/SeqBatchDto.java, src/test/java/ca/gc/aafc/seqdb/api/repository/SeqBatchRepositoryIT.java
https://redmine.biodiversity.agr.gc.ca/issues/23382
=> 23382 fix test issues on dev branch

src/main/java/ca/gc/aafc/seqdb/api/entities/PcrPrimer.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Region.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/PcrPrimerOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/RegionOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/RegionTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23322
=> 23322 missing open api specs to match resource

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/12-Add_new_fields_to_PCRBatch.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23386
=> 23386 add new fields to pcr batch

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrReactionDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrReaction.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/13-Add_columns_to_PcrReaction.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrReactionRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrReactionTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23411
=> 23411 add columns to pcr reaction

src/main/java/ca/gc/aafc/seqdb/api/entities/SeqReaction.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/14-Add_SeqReaction_entity.xml
https://redmine.biodiversity.agr.gc.ca/issues/23413
=> 23413 Add entity seqReaction

src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPoolDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPrepDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/PreLibraryPrepDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PreLibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pooledlibraries/LibraryPool.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/15-Add_group_to_PreLibraryPrep_LibraryPrep_LibraryPool.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/LibraryPoolFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/LibraryPrepFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/PreLibraryPrepFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/23461
=> 23461 pre library prep dto library prep dto and library pool dto missing group field

src/main/java/ca/gc/aafc/seqdb/api/dto/LibraryPrepBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrepBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/16-Add_group_to_LibraryPrepBatch.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/LibraryPrepBatchFactory.java
https://redmine.biodiversity.agr.gc.ca/issues/23483
=> 23483 add group to library prep batch

src/main/java/ca/gc/aafc/seqdb/api/entities/ContainerType.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularSample.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrPrimer.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PreLibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Product.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Protocol.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Region.java, src/main/java/ca/gc/aafc/seqdb/api/entities/ThermocyclerProfile.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/IndexSet.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrep.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/LibraryPrepBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/libraryprep/NgsIndex.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pooledlibraries/LibraryPool.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pooledlibraries/LibraryPoolContent.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/Chain.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/ChainStepTemplate.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/ChainTemplate.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/StepResource.java, src/main/java/ca/gc/aafc/seqdb/api/entities/workflow/StepTemplate.java
https://redmine.biodiversity.agr.gc.ca/issues/23545
=> 23545 Clean entity code

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/17-Add_reactionDate_and_attachments_to_PcrBatch.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23951
=> 23951 add reaction date and attachments to pcr batch

src/main/java/ca/gc/aafc/seqdb/api/dto/PcrBatchItemDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/PcrBatchItem.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrBatchItemRepository.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrBatchItemService.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/18-Add_new_PCRBatchItem.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchItemRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrReactionRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/PcrBatchItemFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchItemTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/23959
=> 23959 add new pcr batch item

pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/24096
=> 24096 update dependencies

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularSampleDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularSample.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/21-Bring_back_SampleType.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleResourceRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/MolecularSampleTestFixture.java
https://redmine.biodiversity.agr.gc.ca/issues/24097
=> 24097 bring back sample type

.gitignore, pom.xml, src/main/resources/db/changelog/db.changelog-init.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/initial-data/1-Initial_workflow_data.xml, src/main/resources/db/changelog/migrations/1-Add_Javers_audit_tables.xml, src/main/resources/db/changelog/migrations/10-update_stepresourcevalue_enum.xml, src/main/resources/db/changelog/migrations/11-Add_seqBatch_entity.xml, src/main/resources/db/changelog/migrations/12-Add_new_fields_to_PCRBatch.xml, src/main/resources/db/changelog/migrations/13-Add_columns_to_PcrReaction.xml, src/main/resources/db/changelog/migrations/14-Add_SeqReaction_entity.xml, src/main/resources/db/changelog/migrations/15-Add_group_to_PreLibraryPrep_LibraryPrep_LibraryPool.xml, src/main/resources/db/changelog/migrations/16-Add_group_to_LibraryPrepBatch.xml, src/main/resources/db/changelog/migrations/17-Add_reactionDate_and_attachments_to_PcrBatch.xml, src/main/resources/db/changelog/migrations/18-Add_new_PCRBatchItem.xml, src/main/resources/db/changelog/migrations/19-Add_ContainerType_to_PCRBatch.xml, src/main/resources/db/changelog/migrations/2-Rename_samples_table.xml, src/main/resources/db/changelog/migrations/20-Add_well_coordinates_PCRBatchItem.xml, src/main/resources/db/changelog/migrations/21-Bring_back_SampleType.xml, src/main/resources/db/changelog/migrations/3-Add_external_relationship_to_MolecularSample.xml, src/main/resources/db/changelog/migrations/4-Update_column_field_targetDpSize_to_targetBpSize.xml, src/main/resources/db/changelog/migrations/5-Remove_SampleType.xml, src/main/resources/db/changelog/migrations/6-Create_PcrBatch_entity.xml, src/main/resources/db/changelog/migrations/7-Rename_PcrProfile_to_ThermocyclerProfile.xml, src/main/resources/db/changelog/migrations/8-Create_PcrReaction_entity.xml, src/main/resources/db/changelog/migrations/9-Add_2_missing_fields_to_PCRBatch.xml, src/main/resources/db/changelog/sample-data/1-Add_Sample_Data.xml
https://redmine.biodiversity.agr.gc.ca/issues/24131
=> 24131 load liquibase xsd from dina base

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/SeqdbApiLauncher.java
https://redmine.biodiversity.agr.gc.ca/issues/24164
=> 24164 update to dina base 0.64

src/main/resources/db/changelog/migrations/22-Change_MolecularSample_to_match_dina_concepts.xml
https://redmine.biodiversity.agr.gc.ca/issues/24184
=> 24184 fix database changelog 22 schema section

pom.xml
https://redmine.biodiversity.agr.gc.ca/issues/25541
=> 25541 update to dina base 0.73

pom.xml, src/main/resources/db/changelog/db.changelog-init.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/initial-data/1-Initial_workflow_data.xml, src/main/resources/db/changelog/migrations/1-Add_Javers_audit_tables.xml, src/main/resources/db/changelog/migrations/10-update_stepresourcevalue_enum.xml, src/main/resources/db/changelog/migrations/11-Add_seqBatch_entity.xml, src/main/resources/db/changelog/migrations/12-Add_new_fields_to_PCRBatch.xml, src/main/resources/db/changelog/migrations/13-Add_columns_to_PcrReaction.xml, src/main/resources/db/changelog/migrations/14-Add_SeqReaction_entity.xml, src/main/resources/db/changelog/migrations/15-Add_group_to_PreLibraryPrep_LibraryPrep_LibraryPool.xml, src/main/resources/db/changelog/migrations/16-Add_group_to_LibraryPrepBatch.xml, src/main/resources/db/changelog/migrations/17-Add_reactionDate_and_attachments_to_PcrBatch.xml, src/main/resources/db/changelog/migrations/18-Add_new_PCRBatchItem.xml, src/main/resources/db/changelog/migrations/19-Add_ContainerType_to_PCRBatch.xml, src/main/resources/db/changelog/migrations/2-Rename_samples_table.xml, src/main/resources/db/changelog/migrations/20-Add_well_coordinates_PCRBatchItem.xml, src/main/resources/db/changelog/migrations/21-Bring_back_SampleType.xml, src/main/resources/db/changelog/migrations/22-Change_MolecularSample_to_match_dina_concepts.xml, src/main/resources/db/changelog/migrations/3-Add_external_relationship_to_MolecularSample.xml, src/main/resources/db/changelog/migrations/4-Update_column_field_targetDpSize_to_targetBpSize.xml, src/main/resources/db/changelog/migrations/5-Remove_SampleType.xml, src/main/resources/db/changelog/migrations/6-Create_PcrBatch_entity.xml, src/main/resources/db/changelog/migrations/7-Rename_PcrProfile_to_ThermocyclerProfile.xml, src/main/resources/db/changelog/migrations/8-Create_PcrReaction_entity.xml, src/main/resources/db/changelog/migrations/9-Add_2_missing_fields_to_PCRBatch.xml, src/main/resources/db/changelog/sample-data/1-Add_Sample_Data.xml
Forced Liquibase version to 4.9.0 so only local XSDs will be loaded. Changed all XSD include to use the one extracted from dina-base.
=> 27552 Update Liquibase

src/main/java/ca/gc/aafc/seqdb/api/dto/sanger/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/sanger/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/external/ExternalResourceProviderImplementation.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/25-Add_storage_unit_to_pcr_batch.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
It is now possible to set an external relationship to a storage-unit from PcrBatch
=> 28015 Add storage external relationship to PcrBatch

src/main/java/ca/gc/aafc/seqdb/api/dto/pcr/PcrBatchItemDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pcr/PcrBatchItem.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/28-Change_PCRBatchItem_materialSample_relationship.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchItemRepositoryIT.java
Replaced PCRBatchItem materialSample by an external relationship
=> 28289 Change PCRBacthItem materialSample relationship

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/entities/StorageRestriction.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/StorageRestrictionFactory.java
Updated dina-base to 0.91, Spring Boot to 2.7.2. Also updated SpotBugs and Checkstyle
=> 28295 Update dina-base and SpringBoot

src/main/java/ca/gc/aafc/seqdb/api/dto/pcr/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pcr/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/external/ExternalResourceProviderImplementation.java, src/main/java/ca/gc/aafc/seqdb/api/service/PcrBatchService.java, src/main/java/ca/gc/aafc/seqdb/api/validation/PcrBatchValidator.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/30-Allow_storage_unit_type_on_pcrbatch.xml, src/main/resources/validation-messages.properties, src/test/java/ca/gc/aafc/seqdb/api/openapi/OpenAPIConstants.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/PcrPrimerOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/RegionOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java
Added new field storageUnitType with a new validator. Cleaned OpenAPI tests so they work like other apis.
=> 28977 Allow to use storage type alone on pcrbatch

pom.xml
Updated dina-base and SpringBoot
=> 29008 Update to dina-base 0.96

src/main/java/ca/gc/aafc/seqdb/api/dto/pcr/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pcr/PcrBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/35-Add_protocol_PCRBatch.xml, src/test/java/ca/gc/aafc/seqdb/api/openapi/PcrBatchOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java
Added missing protocol external relationship to PCR Batch
=> 30003 PCRBatch missing protocol

src/main/java/ca/gc/aafc/seqdb/api/dto/RegionDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/Region.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/RegionTestFixture.java
The field was already available on the entity so I only exposed it in the DTO
=> 30077 Access to the Region Applicable Organisms Field through the API

src/main/java/ca/gc/aafc/seqdb/api/entities/ThermocyclerProfile.java
createdOn was set but not returned on create
=> 30138 Thermocycler Profile created on not being set automatically

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/SequenceVocabularyConfiguration.java, src/main/java/ca/gc/aafc/seqdb/api/dto/VocabularyDto.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainStepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ChainTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ContainerTypeRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/IndexSetRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolContentRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPoolRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/LibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/MolecularSampleRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/NgsIndexRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrBatchItemRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PcrPrimerRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/PreLibraryPrepRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ProductRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/RegionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/SeqBatchRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/SeqReactionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/SeqSubmissionRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/SequencingFacilityRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepResourceRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/StepTemplateRepository.java, src/main/java/ca/gc/aafc/seqdb/api/repository/ThermocyclerProfileRepository.java, src/main/resources/application.yml, src/main/resources/vocabulary/pcrType.yml
Updated dina-base, SpringBoot and related code
=> 30687 Update dependencies

src/main/java/ca/gc/aafc/seqdb/api/SequenceVocabularyConfiguration.java, src/main/java/ca/gc/aafc/seqdb/api/dto/pcr/PcrBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pcr/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/validation/PcrBatchValidator.java, src/main/java/ca/gc/aafc/seqdb/api/validation/PcrBatchVocabularyValidator.java, src/main/java/ca/gc/aafc/seqdb/api/validation/VocabularyBasedValidator.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/37-Add_batchType_to_PCRBatch.xml, src/main/resources/validation-messages.properties, src/main/resources/vocabulary/pcrBatchType.yml, src/test/java/ca/gc/aafc/seqdb/api/SequenceModuleBaseIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/VocabularyRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/PcrBatchFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/PcrBatchTestFixture.java, src/test/java/ca/gc/aafc/seqdb/api/validation/PcrBatchValidationTest.java
Added PCR Batch Type + validation
=> 30575 Add PCR Batch Type Field to PCR Batches

src/main/java/ca/gc/aafc/seqdb/api/SequenceVocabularyConfiguration.java, src/main/java/ca/gc/aafc/seqdb/api/dto/SeqBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/dto/SeqReactionDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/SeqBatch.java, src/main/java/ca/gc/aafc/seqdb/api/entities/pcr/PcrBatch.java, src/main/java/ca/gc/aafc/seqdb/api/validation/PcrBatchVocabularyValidator.java, src/main/java/ca/gc/aafc/seqdb/api/validation/SeqBatchValidator.java, src/main/java/ca/gc/aafc/seqdb/api/validation/SeqBatchVocabularyValidator.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/38-Add_sequencingType_to_SeqBatch.xml, src/main/resources/vocabulary/pcrBatchType.yml, src/main/resources/vocabulary/sequencingType.yml, src/test/java/ca/gc/aafc/seqdb/api/repository/SeqSubmissionRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/repository/VocabularyRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/SeqBatchTestFixture.java, src/test/java/ca/gc/aafc/seqdb/api/validation/SeqBatchValidationTest.java
=> 30660 Add Sequencing Type to SeqBatch

src/main/java/ca/gc/aafc/seqdb/api/dto/SeqBatchDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/SeqBatch.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/39-Add_isCompleted_to_SeqBatch.xml
Added isCompleted flag to SeqBatch
=> 30707 Add the ability to mark SeqBatch as Complete

src/test/java/ca/gc/aafc/seqdb/api/openapi/OpenAPIConstants.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/SeqSubmissionOpenApiIT.java
Based on https://github.com/DINA-Web/sequence-specs/pull/12
=> 30710: Creation of SeqSumissionOpenApi

src/main/java/ca/gc/aafc/seqdb/api/dto/SeqReactionDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/SeqReaction.java, src/main/java/ca/gc/aafc/seqdb/api/service/SeqReactionService.java
Added calculated field cellNumber to SeqReaction
=> 31586 Add cellNumber to SeqReaction response

pom.xml
Updated dina-base, SpringBoot, dependency-check
=> 31631 Update dependencies

src/main/resources/db/changelog/migrations/43-Change_PcrBatchItem_to_use_StorageUnitUsage.xml, src/main/resources/db/changelog/migrations/44-Change_SeqReaction_to_use_StorageUnitUsage.xml
Added precondition to db migration
=> 34361 Avoid drop column in migration if there is content

src/main/java/ca/gc/aafc/seqdb/api/dto/IndexSetDto.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/IndexSetOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/IndexSetTestFixture.java
Added Integration Test and corresponding Fixture
=> Support #35013 - Add OpenAPI specs to Integration Test for IndexSet

src/main/java/ca/gc/aafc/seqdb/api/dto/NgsIndexDto.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/NgsIndexOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/NgsIndexTestFixture.java
Added NGS Index Open API Integration Test and its corresponding fixture
=> 35036 add open api specs to integration test for ngs index

src/main/java/ca/gc/aafc/seqdb/api/dto/ThermocyclerProfileDto.java, src/test/java/ca/gc/aafc/seqdb/api/openapi/ThermocyclerProfileOpenApiIT.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/ThermocyclerProfileTestFixture.java
Added integration test and edited fixture and dto for thermocyclerProfile
=> Support_30856_Add_ThermocyclerProfile_specs_+_test

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularAnalysisRunItemDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularAnalysisRunItem.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/52-Add_type_to_MolecularAnalysisRunItem.xml, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/MolecularAnalysisRunItemFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/MolecularAnalysisRunItemTestFixture.java
=> 35222 Add type to MolecularAnalysisRunItem

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularAnalysisRunDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularAnalysisRun.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/53-Add_attachments_to_MolecularAnalysisRun.xml
Added column and updated entity/dto
=> 35217 Add attachments to MolecularAnalysisRun

src/main/resources/vocabulary/pcrBatchType.yml
Replaced round 2 with Illumina Metagenomics
=> 35321 Change pcrBatch type vocabulary

src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java, src/main/java/ca/gc/aafc/seqdb/api/dto/GenericMolecularAnalysisDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/GenericMolecularAnalysis.java, src/main/java/ca/gc/aafc/seqdb/api/service/GenericMolecularAnalysisService.java, src/main/java/ca/gc/aafc/seqdb/api/util/ManagedAttributeIdMapper.java, src/main/java/ca/gc/aafc/seqdb/api/validation/SequenceManagedAttributeValueValidator.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/56-Add_managed_attribute_to_molecular_analysis.xml, src/test/java/ca/gc/aafc/seqdb/api/repository/SequenceManagedAttributeRepositoryIT.java, src/test/java/ca/gc/aafc/seqdb/api/service/GenericMolecularAnalysisServiceIT.java, src/test/java/ca/gc/aafc/seqdb/api/service/SequenceManagedAttributeServiceIT.java
=> 35302 Add managed attribute usage on generic molecular analysis

src/main/java/ca/gc/aafc/seqdb/api/dto/MolecularAnalysisRunItemDto.java, src/main/java/ca/gc/aafc/seqdb/api/entities/MolecularAnalysisRunItem.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/58-Add_name_to_MolecularAnalysisRunItem.xml, src/test/java/ca/gc/aafc/seqdb/api/testsupport/factories/MolecularAnalysisRunItemFactory.java, src/test/java/ca/gc/aafc/seqdb/api/testsupport/fixtures/MolecularAnalysisRunItemTestFixture.java
- Added name field to MolecularRunItemDto and MolecularAnalysisRunItem
=> 35373 Add name to molecular analysis run item

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/ResourceRepositoryConfig.java, src/main/java/ca/gc/aafc/seqdb/api/config/SearchQueueProperties.java, src/main/java/ca/gc/aafc/seqdb/api/messaging/SearchRabbitMQMessageProducer.java, src/main/java/ca/gc/aafc/seqdb/api/service/MolecularAnalysisRunService.java, src/main/resources/application.yml
Added configuration to emit messages on molecular-analysis-run changes
=> 35692 Add message producer

pom.xml, src/main/java/ca/gc/aafc/seqdb/api/entities/SeqSubmission.java, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/migrations/59-Increase_name_length_seq_submission.xml
Increased name length to 150 chars for name on Seq Submission
=> 36490 SEQ Submission 50-Character Limit
